import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('publisher 0.4.0 публикует полный проверяемый набор release assets', async () => {
  const source = await readFile('.github/workflows/release.yml', 'utf8');
  assert.match(source, /--target "\$SOURCE_SHA"/u);
  assert.match(source, /"\$ARCHIVE"/u);
  assert.match(source, /"\$ARCHIVE\.sha256"/u);
  assert.match(source, /install-kafedra-planner\.sh/u);
  assert.match(source, /README-INSTALL\.txt/u);
  assert.match(source, /kafedra-planner-\$\{VERSION\}-project-control\.f2re\.zip/u);
  assert.match(source, /kafedra-planner-\$\{VERSION\}-project-control\.f2re\.zip\.sha256/u);
  assert.match(source, /SHA256SUMS/u);
  assert.match(source, /sha256sum -c --strict SHA256SUMS/u);
  assert.match(source, /gh release create "\$TAG"/u);
  assert.match(source, /--draft/u);
  assert.match(source, /gh release upload "\$TAG" "\$file"/u);
  assert.match(source, /for attempt in 1 2 3/u);
  assert.match(source, /--json databaseId,isDraft/u);
  assert.match(source, /releases\/\$RELEASE_ID\/assets\?per_page=100/u);
  assert.match(source, /--method DELETE "repos\/\$GITHUB_REPOSITORY\/releases\/\$RELEASE_ID"/u);
  assert.match(source, /\.target_commitish/u);
  assert.match(source, /"\$ACTUAL_NAMES" == "\$EXPECTED_NAMES"/u);
  assert.match(source, /stat -c%s "\$asset"/u);
  assert.match(source, /"\$actual_size" == "\$expected_size"/u);
  assert.match(source, /--method PATCH "repos\/\$GITHUB_REPOSITORY\/releases\/\$RELEASE_ID"/u);
  assert.match(source, /-F draft=false -f make_latest=true/u);
  assert.doesNotMatch(source, /--cleanup-tag/u);
  assert.match(source, /select\(\.state == "uploaded"\)/u);
  assert.match(source, /"\$ACTUAL_ASSETS" == "\$EXPECTED_ASSETS"/u);
  assert.match(source, /\[\[ "\$OBJECT_SHA" == "\$SOURCE_SHA" \]\]/u);
  assert.doesNotMatch(source, /--prerelease/u);
});
